apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    metadata:
      annotations:
        # https://www.vaultproject.io/docs/platform/k8s/injector/annotations
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'example-role1'
        vault.hashicorp.com/agent-inject-secret-config: 'dev/data/modio-common'
        vault.hashicorp.com/agent-init-first: 'true'
