on:
  workflow_dispatch:
    inputs:
      sleep:
        default: '0'
        type: number
        description: 'Time to pause'
        
jobs:
  nothing:
    runs-on: custom-runner1
    steps:
      - run: |
          pwd
          whoami
          ls -l
          sleep ${{ inputs.sleep }}
