on:
  push:
    branches:
      - develop

jobs:
  runs-on: self-hosted
  steps:
    - run: |
        echo running in self hosted
        whoami
        pwd
        ls -l
  #test1:
  #  uses: ModioHealth/argocd/.github/workflows/test.yml@master
    
